input: samplesheet_merged.csv
outdir: ./results_EBV
#genome: GRCh38
fasta: ./data/GRCh38.primary_assembly.genome.fa
gtf: ./data/gencode.v46.primary_assembly.basic.annotation.gtf
#viral_fasta: ./path/to/EBV_fasta/GCF_002402265.1_ASM240226v1_genomic.fna # uncomment if EBV search only, fill in correct path to downloaded fasta file. downloaded from https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/002/402/265/GCF_002402265.1_ASM240226v1/
email: your_email
#multiqc_title: 
#min_reads: 5
#max_hits: 50
#remove_duplicates: true
